version: '3'

volumes:
  keys:
  cargo-registry:
  cargo-git:
  cargo-target:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true 

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
    volumes:
      - influxdb-volume:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
  validator-0:
    image: hyperledger/sawtooth-all:1.1
    container_name: sawtooth-shell-default
    expose:
      - 4004
      - 5050
      - 8800
    volumes: 
      - ./Assets:/var/Assets
      - keys:/shared_keys
    command: "bash -c \"\
        sawadm keygen validator-1 && \
        sawadm keygen validator-2 && \
        sawadm keygen validator-3 && \
        sawadm keygen && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=pbft \
          sawtooth.consensus.algorithm.version=0.1 \
          sawtooth.consensus.pbft.members=\\['\\\"'$$(cat /etc/sawtooth/keys/validator.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-1.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-2.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-3.pub)'\\\"'\\] \
          sawtooth.consensus.pbft.block_duration=100 \
          sawtooth.consensus.pbft.view_change_timeout=4000 \
          sawtooth.consensus.pbft.message_timeout=10 \
          sawtooth.consensus.pbft.max_log_size=1000 \
          -o config.batch && \
        sawadm genesis \
          config-genesis.batch config.batch && \
        mv /etc/sawtooth/keys/validator-* /shared_keys && \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --scheduler parallel \
            --maximum-peer-connectivity 3 \
            --opentsdb-db telegraf \
            --opentsdb-url http://influxdb:8086 \
    \""
  pbft-0:
    image: sawtooth-pbft-engine-local
    build:
      context: ./sawtooth-pbft
      dockerfile: ./sawtooth-pbft/Dockerfile
    volumes:
      - ./sawtooth-pbft:/project/sawtooth-pbft
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
    working_dir: /project/sawtooth-pbft/
    command: ./target/debug/pbft-engine --connect tcp://validator-0:5050 -vv
    stop_signal: SIGKILL
